TEST_API_KEY = "xxx"
TEST_RESELLER_ID = "xxx"
TEST_RESELLER_GENCOD = nil

TEST_CUSTOMER_UID = "IMORDERCUST#{Time.now.to_i}"
TEST_ORDER_UID = "IMORDERORD#{Time.now.to_i}"

TEST_MISSING_CUSTOMER_UID = "IMORDERCUSTMISSING"
TEST_MISSING_ORDER_UID = "IMORDERMISSING"

